# Generated by Django 4.1 on 2022-10-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsdata', '0002_note_created_note_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_note',
        ),
        migrations.AddField(
            model_name='job',
            name='note_name',
            field=models.TextField(blank=True, default='Applied!', null=True),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
